module.exports = {
    Feature: 'Feature',
    Rule: 'Rule',
    Background: 'Background',
    Scenario: 'Scenario',
    Example: 'Example',
    'Scenario Outline': 'Scenario Outline',
    'Scenario Template': 'Scenario Template',
    Examples: 'Examples',
    Scenarios: 'Scenarios',
    Given: 'Given',
    When: 'When',
    Then: 'Then',
    And: 'And',
    But: 'But',
    tag: '@',
    comment: '#',
    docstring: '"""',
    datatable: '|',
};
