name: build-and-package

on:
    push:
        branches:
            - main

jobs:
    build-package:
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v2

            - name: node
              uses: actions/setup-node@v1
              with:
                  node-version: 14

            - name: npm install
              run: npm ci

            - name: build
              run: npm run build:prod

            - name: package
              run: npm run package
