name: build-and-package

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    release:
        types:
            - created

jobs:
    build-and-package:
        runs-on: ubuntu-latest

        steps:
            - name: checkout
              uses: actions/checkout@v2

            - name: node
              uses: actions/setup-node@v1
              with:
                  node-version: 14

            - name: npm install
              run: npm ci

            - name: build
              run: npm run build

            - name: package-extension
              run: npm run package

            - name: publish
              if: success() && startsWith(github.ref, 'refs/tags/releases/')
              run: npm run deploy
              env:
                  VSCE_PAT: ${{ secrets.VSCE_PAT }}
