name: test-build-package-release

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
    release:
        types: [published]

jobs:
    test-build-package-release:
        runs-on: ubuntu-latest

        steps:
            - name: Cancel previous runs
              uses: styfle/cancel-workflow-action@0.9.1
              with:
                all_but_latest: true
                access_token: ${{ secrets.GITHUB_TOKEN }}
                
            - name: checkout
              uses: actions/checkout@v2

            - name: node
              uses: actions/setup-node@v1
              with:
                  node-version: 14

            - name: npm install
              run: npm ci

            - name: unit-tests
              run: npm run test:unit

            - name: build
              run: npm run build:prod

            - name: package
              run: npm run package

            - name: upload-artifacts
              if: success() && startsWith(github.ref, 'refs/tags/')
              uses: fnkr/github-action-ghr@v1
              env:
                  GHR_PATH: packages/
                  GHR_REPLACE: true
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: publish
              if: success() && startsWith(github.ref, 'refs/tags/')
              run: npm run deploy
              env:
                  VSCE_PAT: ${{ secrets.VSCE_PAT }}
